basic:
  fragments:
    - basic

# The 'ruby' fragment depends on the 'basic' fragment
ruby:
  fragments:
    - basic
    - ruby


# Demonstrates the 'credit' ERB fragment
credit:
  fragments:
    - basic
    - credit

couchdb:
  fragments:
    - basic
    - ruby
    - couchdb

